# Generated by Django 3.0.6 on 2020-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=88)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
