# Generated by Django 3.0.6 on 2020-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0002_auto_20200602_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='date',
            field=models.DateField(),
        ),
    ]
