# Generated by Django 3.0.6 on 2020-06-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0003_auto_20200602_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogapp',
            name='img',
        ),
    ]
